
services:
  web:
    image: odoo:17.0
    command: ["sh", "-c", "pip install pyjwt | grep -v 'already satisfied'; odoo --db_host=db --db_port=5432 --db_user=odoo --db_password=odoo"]
    depends_on:
      - db
    ports:
      - "8017:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD=odoo
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:

